name: aggregator
on:
  workflow_dispatch:
jobs:
  aggregate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout aggregator repo
        uses: actions/checkout@v4

      # Download artifact from Repo A
      - name: Download RepoA docs
        uses: actions/download-artifact@v4
        with:
          name: repoA-docs
          path: imported_artifacts/repoA-docs
        # If you need from a different repo, you might specify 'workflow' / 'run-id' / 'repository' inputs

      # Download artifact from Repo B
      - name: Download RepoB docs
        uses: actions/download-artifact@v4
        with:
          name: repoB-docs
          path: imported_artifacts/repoB-docs
        # Similarly, specify the right source repo if needed

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install sphinx sphinx_needs

      - name: Build aggregator docs
        run: |
          sphinx-build -b html aggregator aggregator/_build/html

      - name: Upload aggregator artifact
        uses: actions/upload-artifact@v4
        with:
          name: aggregator-docs
          path: aggregator/_build/html

    
      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: aggregator/_build/html
